### ISSUE TITLE
Qt.QtCompat.loadUi was broken in Nuke with Qt.py release 1.0.0b4

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#208]
We've been running Qt.py 1.0.0b3 in production for some time now without any issues. When I gave PR https://github.com/mottosso/Qt.py/pull/190 a spin, I noticed I got errors in Nuke 9.0v9.

When digging further, it seems that the issue stems from changes implemented in Qt.py 1.0.0b4.

### Error

```
# Result: Traceback (most recent call last):
  File "<string>", line 72, in <module>
  File "<string>", line 69, in __init__
  File "/Users/fredrik/miniconda3/envs/Qtdev_py27/lib/python2.7/site-packages/Qt.py", line 1028, in _loadUi
    Qt.QtCore.QMetaObject.connectSlotsByName(widget)
RuntimeError: Internal C++ object (PySide.QtGui.QMainWindow) already deleted.
```

![screen shot 2017-05-31 at 08 20 47](https://cloud.githubusercontent.com/assets/994357/26618716/a0c53e92-45db-11e7-8e04-594ee43d49cd.png)

### Reproducible code 

This reproducible code runs fine in e.g. Maya but will crash in Nuke when using Qt.py 1.0.0b4:

#### Run from Nuke script editor

```python
import tempfile
import os
import io

from Qt import QtWidgets
from Qt import QtCompat

TEMPDIR = tempfile.mkdtemp()
tempfile = os.path.join(TEMPDIR, "qmainwindow.ui")

with io.open(tempfile, "w", encoding="utf-8") as f:
    f.write(u"""\
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>223</width>
    <height>140</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <widget class="QPushButton" name="pushButton">
    <property name="geometry">
     <rect>
      <x>70</x>
      <y>40</y>
      <width>80</width>
      <height>16</height>
     </rect>
    </property>
    <property name="text">
     <string>PushButton</string>
    </property>
   </widget>
  </widget>
  <widget class="QMenuBar" name="menubar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>223</width>
     <height>17</height>
    </rect>
   </property>
  </widget>
  <widget class="QStatusBar" name="statusbar"/>
 </widget>
 <resources/>
 <connections/>
</ui>
""")


class MyWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(MyWindow, self).__init__(parent)
        self.main_widget = QtCompat.loadUi(tempfile)
        self.setCentralWidget(self.main_widget)

my_window = MyWindow()
my_window.show()
```

### Install the problematic Qt.py version

    pip install Qt.py==1.0.0b4

@mottosso I'm labeling this as a bug. Do you have any ideas on why this may be happening or should I check with Foundry Support?

**Comment by mottosso** [comment]
Does it crash outside of Nuke?

If not, we should try and reproduce it without Qt.py before submitting to Foundry.

**Comment by fredrikaverpil** [comment]
When running this outside of Nuke using PySide 1.2.4, Python crashes. It's a bit different than when you run the code in Nuke as you have to create QApplication (I added this code to the original post at the top). The window shows but is unresponsive and does not show with the UI file loaded (just an empty window). No traceback is printed out.

I tested this using the following conda environment on Windows (Powershell):

```bash
conda create -n pysidedev_py27 python=2.7 pyside
~/.conda/envs/pyside_py27/Scripts/pip.exe install Qt.py==1.0.0b4
```

**Comment by fredrikaverpil** [comment]
My bad!
I forgot to add `sys.exit(app.exec_())` after `window.show()`. This does **not** crash when run in standalone Python interpreter using PySide 1.2.4 and Qt.py 1.0.0b4:

```python
import sys
import tempfile
import os
import io

from Qt import QtWidgets
from Qt import QtCompat

TEMPDIR = tempfile.mkdtemp()
tempfile = os.path.join(TEMPDIR, "qmainwindow.ui")

with io.open(tempfile, "w", encoding="utf-8") as f:
    f.write(u"""\
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>223</width>
    <height>140</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <widget class="QPushButton" name="pushButton">
    <property name="geometry">
     <rect>
      <x>70</x>
      <y>40</y>
      <width>80</width>
      <height>16</height>
     </rect>
    </property>
    <property name="text">
     <string>PushButton</string>
    </property>
   </widget>
  </widget>
  <widget class="QMenuBar" name="menubar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>223</width>
     <height>17</height>
    </rect>
   </property>
  </widget>
  <widget class="QStatusBar" name="statusbar"/>
 </widget>
 <resources/>
 <connections/>
</ui>
""")


class MyWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(MyWindow, self).__init__(parent)
        self.main_widget = QtCompat.loadUi(tempfile)
        self.setCentralWidget(self.main_widget)

app = QtWidgets.QApplication(sys.argv)
my_window = MyWindow()
my_window.show()
sys.exit(app.exec_())
```

![image](https://cloud.githubusercontent.com/assets/994357/26621344/d47172a0-45e6-11e7-9794-d54442d064dd.png)

**Comment by bpabel** [comment]
I've noticed this happening in nuke if the python reference to the window or its parent goes out of scope.  I generally have to create a global reference to the window, or if it's parented to the main nuke window, a global reference to that.

**Comment by fredrikaverpil** [comment]
@bpabel i just ran the following (as per your suggestion) in Nuke 9.0v9, with the same error as before:

```python
import tempfile
import os
import io

from Qt import QtWidgets
from Qt import QtCompat

TEMPDIR = tempfile.mkdtemp()
tempfile = os.path.join(TEMPDIR, "qmainwindow.ui")

with io.open(tempfile, "w", encoding="utf-8") as f:
    f.write(u"""\
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>MainWindow</class>
 <widget class="QMainWindow" name="MainWindow">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>223</width>
    <height>140</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>MainWindow</string>
  </property>
  <widget class="QWidget" name="centralwidget">
   <widget class="QPushButton" name="pushButton">
    <property name="geometry">
     <rect>
      <x>70</x>
      <y>40</y>
      <width>80</width>
      <height>16</height>
     </rect>
    </property>
    <property name="text">
     <string>PushButton</string>
    </property>
   </widget>
  </widget>
  <widget class="QMenuBar" name="menubar">
   <property name="geometry">
    <rect>
     <x>0</x>
     <y>0</y>
     <width>223</width>
     <height>17</height>
    </rect>
   </property>
  </widget>
  <widget class="QStatusBar" name="statusbar"/>
 </widget>
 <resources/>
 <connections/>
</ui>
""")


class MyWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(MyWindow, self).__init__(parent)
        self.main_widget = QtCompat.loadUi(tempfile)
        self.setCentralWidget(self.main_widget)


global nuke_window
nuke_window = QtWidgets.QApplication.activeWindow()

my_window = MyWindow(nuke_window)
my_window.show()
```

**Comment by fredrikaverpil** [comment]
By the way, I believe the widget which disappears is the mainwindow from my UI file. Not the Nuke main window.

I tried this inside of Qt.py:

```python
        global widget
        widget = _UiLoader(baseinstance).load(uifile)
        Qt.QtCore.QMetaObject.connectSlotsByName(widget)

        return widget
```

However, that resulted in the same error as before:

```
Traceback (most recent call last):
  File "<string>", line 77, in <module>
  File "<string>", line 70, in __init__
  File "/Users/fredrik/miniconda3/envs/Qtdev_py27/lib/python2.7/site-packages/Qt.py", line 1029, in _loadUi
    Qt.QtCore.QMetaObject.connectSlotsByName(widget)
RuntimeError: Internal C++ object (PySide.QtGui.QMainWindow) already deleted.
```

**Comment by fredrikaverpil** [comment]
@bpabel however, I think you're on to something here. It clearly seems like a reference to the widget is lost and therefore PySide/Nuke is removed.

**Comment by fredrikaverpil** [comment]
This issue is not present in Nuke 10.0v6.

**Comment by fredrikaverpil** [comment]
Nuke 9.0v9 PySide version: 1.0.9
Nuke 10.0v6 PySide version: 1.2.2

**Comment by fredrikaverpil** [comment]
Perhaps related: https://bugreports.qt.io/browse/PYSIDE-10

**Comment by fredrikaverpil** [comment]
I just heard back from the Foundry developers:

> I've come across a number of issues like this in PySide. For example, you get the same exception thrown if you use anything returned by QWidget.parentWidget or QWidget.findChild. This is a known bug in PySide (https://bugreports.qt.io/browse/PYSIDE-10).

> they've managed to create a workaround for it now. And the bug is fixed in later versions of PySide, so only affects Nuke 9, which was using the older PySide 1.0.9."

This is good to know as it's not only a bug in Nuke 9 but also could exist in other applications running this older PySide version.
