### ISSUE TITLE
Can't import QtWidgets in Maya 2017

### ISSUE THREAD

**Issue by phimath** [mottosso/Qt.py#317]
In Maya 2017:
```
from Qt import QtWidgets
# Error: ImportError: file <maya console> line 1: cannot import name QtWidgets # 
```

But I can import Qt:

```
import Qt

dir(Qt)
# Result: ['IsPyQt4', 'IsPyQt5', 'IsPySide', 'IsPySide2', 'QT_PREFERRED_BINDING', 'QT_SIP_API_HINT', 'QT_VERBOSE', 'Qt', 'QtCompat', '__all__', '__binding__', '__binding_version__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__version__', '_apply_site_config', '_build_compatibility_members', '_cli', '_common_members', '_compatibility_members', '_convert', '_import_sub_module', '_install', '_loadUi', '_log', '_misplaced_members', '_new_module', '_none', '_pyqt4', '_pyqt5', '_pyside', '_pyside2', '_qInstallMessageHandler', '_reassign_misplaced_members', '_setup', '_wrapinstance', 'os', 'shutil', 'sys', 'types'] # 
Qt.IsPySide2
# Result: True # 

```

Qt.py works fine in other software, why am I having this issue in Maya?

**Comment by mottosso** [comment]
Try this.

```python
from PySide2 import QtWidgets
```

**Comment by phimath** [comment]
```
from PySide2 import QtWidgets
# Error: ImportError: file <maya console> line 1: libpyside2-python2.7.so.2.0: cannot open shared object file: No such file or directory # 
```
But, I set QT_VERBOSE and now I think its something to do with my Maya installation and not Qt.py because I get:
```
Trying PySide2
# Error: root : code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/autodesk/maya2017/lib/python27.zip/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/autodesk/maya2017/lib/python27.zip/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5 # 
```

**Comment by phimath** [comment]
I've resolved all of these issues.  They all stemmed from running Maya on Ubuntu and not from Qt.py.

Got everything working though.
